### ISSUE TITLE
CursorIndexOutOfBoundsException

### ISSUE THREAD

**Issue by lingling-fan** [wistein/TransektCount#5]
//package name: com.wmstein.transektcount
//version: 2.0.0
 android.database.CursorIndexOutOfBoundsException: Index 0 requested, with a size of 0
 	at android.database.AbstractCursor.checkPosition(AbstractCursor.java:424)
 	at android.database.AbstractWindowedCursor.checkPosition(AbstractWindowedCursor.java:136)
 	at android.database.AbstractWindowedCursor.getInt(AbstractWindowedCursor.java:68)
 	at com.wmstein.transektcount.database.SectionDataSource.cursorToSection(SectionDataSource.java:66)
 	at com.wmstein.transektcount.database.SectionDataSource.getSection(SectionDataSource.java:182)
 	at com.wmstein.transektcount.NewSectionActivity.compSectionNames(NewSectionActivity.java:173)
 	at com.wmstein.transektcount.NewSectionActivity.saveSection(NewSectionActivity.java:128)
 	at com.wmstein.transektcount.NewSectionActivity.onOptionsItemSelected(NewSectionActivity.java:112)
 	at android.app.Activity.onMenuItemSelected(Activity.java:2566)
 	at android.support.v4.app.FragmentActivity.onMenuItemSelected(FragmentActivity.java:403)
 	at android.support.v7.app.AppCompatActivity.onMenuItemSelected(AppCompatActivity.java:189)
 	at android.support.v7.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:100)
 	at android.support.v7.app.AppCompatDelegateImplV7.onMenuItemSelected(AppCompatDelegateImplV7.java:663)
 	at android.support.v7.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:811)
 	at android.support.v7.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:152)
 	at android.support.v7.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:958)
 	at android.support.v7.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:948)
 	at android.support.v7.widget.ActionMenuView.invokeItem(ActionMenuView.java:618)
 	at android.support.v7.view.menu.ActionMenuItemView.onClick(ActionMenuItemView.java:139)
 	at android.view.View.performClick(View.java:4240)
 	at android.view.View.onKeyUp(View.java:7928)
 	at android.widget.TextView.onKeyUp(TextView.java:5552)
 	at android.view.KeyEvent.dispatch(KeyEvent.java:2647)
 	at android.view.View.dispatchKeyEvent(View.java:7343)
 	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1393)
 	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1393)
 	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1393)
 	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1393)
 	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1393)
 	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1393)
 	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1393)
 	at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchKeyEvent(PhoneWindow.java:1933)
 	at com.android.internal.policy.impl.PhoneWindow.superDispatchKeyEvent(PhoneWindow.java:1408)
 	at android.app.Activity.dispatchKeyEvent(Activity.java:2384)
 	at android.support.v7.app.AppCompatActivity.dispatchKeyEvent(AppCompatActivity.java:534)
 	at android.support.v7.view.WindowCallbackWrapper.dispatchKeyEvent(WindowCallbackWrapper.java:50)
 	at android.support.v7.app.AppCompatDelegateImplBase$AppCompatWindowCallbackBase.dispatchKeyEvent(AppCompatDelegateImplBase.java:241)
 	at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchKeyEvent(PhoneWindow.java:1860)
 	at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:3791)
 	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:3774)
 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3379)
 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3429)
 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3398)
 	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3483)
 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3406)
 	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3540)
 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3379)
 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3429)
 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3398)

**Comment by lingling-fan** [comment]
**Pkg**: com.wmstein.transektcount
**Exception**: android.database.CursorIndexOutOfBoundsException: Index 0 requested, with a size of 0
**Category**: Index error
**Root cause**: The cursor in Method "com.wmstein.transektcount.database.SectionDataSource.getSection(at line 181)" has not check if the access line exists or not, missing "if (cursor.moveToFirst())" probably.
**Description**: When querying database, it may failed, better to check whether the return value is null or not; Besides, the cursor is at index -1 by default, call "MoveToFirst()" before data access and also check if it's empty. \nNote: "null" and "empty" are different. 
**Fix solution**: 
    1: Use if((cursor != null) and (!cursor.MoveToFirst())) to check.
    2: Use while(!cursor.MoveToNext()) to iterate when using loop clause.

**Comment by wistein** [comment]
Fixed with commit badc113.
