### ISSUE TITLE
IllegalStateException: attempt to re-open an already-closed object

### ISSUE THREAD

**Issue by lingling-fan** [wistein/TransektCount#7]
//package name: com.wmstein.transektcount
//version: 2.0.0
 java.lang.IllegalStateException: attempt to re-open an already-closed object: SQLiteDatabase: /data/data/com.wmstein.transektcount/databases/transektcount.db
 	at android.database.sqlite.SQLiteClosable.acquireReference(SQLiteClosable.java:55)
 	at android.database.sqlite.SQLiteDatabase.updateWithOnConflict(SQLiteDatabase.java:1543)
 	at android.database.sqlite.SQLiteDatabase.update(SQLiteDatabase.java:1520)
 	at com.wmstein.transektcount.database.HeadDataSource.saveHead(HeadDataSource.java:48)
 	at com.wmstein.transektcount.EditMetaActivity.saveData(EditMetaActivity.java:227)
 	at com.wmstein.transektcount.EditMetaActivity.onOptionsItemSelected(EditMetaActivity.java:273)
 	at android.app.Activity.onMenuItemSelected(Activity.java:2566)
 	at android.support.v4.app.FragmentActivity.onMenuItemSelected(FragmentActivity.java:403)
 	at android.support.v7.app.AppCompatActivity.onMenuItemSelected(AppCompatActivity.java:189)
 	at android.support.v7.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:100)
 	at android.support.v7.app.AppCompatDelegateImplV7.onMenuItemSelected(AppCompatDelegateImplV7.java:663)
 	at android.support.v7.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:811)
 	at android.support.v7.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:152)
 	at android.support.v7.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:958)
 	at android.support.v7.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:948)
 	at android.support.v7.widget.ActionMenuView.invokeItem(ActionMenuView.java:618)
 	at android.support.v7.view.menu.ActionMenuItemView.onClick(ActionMenuItemView.java:139)
 	at android.view.View.performClick(View.java:4240)
 	at android.view.View.onKeyUp(View.java:7928)
 	at android.widget.TextView.onKeyUp(TextView.java:5552)
 	at android.view.KeyEvent.dispatch(KeyEvent.java:2647)
 	at android.view.View.dispatchKeyEvent(View.java:7343)
 	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1393)
 	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1393)
 	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1393)
 	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1393)
 	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1393)
 	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1393)
 	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1393)
 	at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchKeyEvent(PhoneWindow.java:1933)
 	at com.android.internal.policy.impl.PhoneWindow.superDispatchKeyEvent(PhoneWindow.java:1408)
 	at android.app.Activity.dispatchKeyEvent(Activity.java:2384)
 	at android.support.v7.app.AppCompatActivity.dispatchKeyEvent(AppCompatActivity.java:534)
 	at android.support.v7.view.WindowCallbackWrapper.dispatchKeyEvent(WindowCallbackWrapper.java:50)
 	at android.support.v7.app.AppCompatDelegateImplBase$AppCompatWindowCallbackBase.dispatchKeyEvent(AppCompatDelegateImplBase.java:241)
 	at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchKeyEvent(PhoneWindow.java:1860)
 	at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:3791)
 	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:3774)
 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3379)
 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3429)
 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3398)
 	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3483)
 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3406)
 	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3540)
 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3379)
 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3429)
 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3398)
 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3406)
 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3379)

**Comment by wistein** [comment]
Database related errors can occur when trying to use a databse created by an older app version or vice versa.
So please, use the latest version and a provided example database as a starting point or create a new from scratch. 
I will look into this to fix the exeptions asap.

**Comment by wistein** [comment]
Fixed with commit badc113.
